## 1.1 Matrices

In [1]:
import numpy as np

In [2]:
arr = [[1, 2], [3, 4]]
print(arr)

[[1, 2], [3, 4]]


In [3]:
# Convert to NumPy
np.array(arr)

array([[1, 2],
       [3, 4]])

In [4]:
import torch

In [5]:
torch.Tensor(arr)


 1  2
 3  4
[torch.FloatTensor of size 2x2]

## 1.2 Matrices with Default Values

In [6]:
torch.ones((2, 2))


 1  1
 1  1
[torch.FloatTensor of size 2x2]

In [7]:
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

In [8]:
torch.rand(2, 2)


 0.1183  0.8181
 0.7281  0.8994
[torch.FloatTensor of size 2x2]

In [9]:
np.random.rand(2, 2)


array([[0.97844378, 0.76618141],
       [0.84597044, 0.8921559 ]])

## 1.3 Seeds for Reproducibility

In [10]:
np.random.seed(0)
np.random.rand(2, 2)

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318]])

In [11]:
np.random.seed(0)
np.random.rand(2, 2)

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318]])

In [12]:
np.random.rand(2, 2)

array([[0.4236548 , 0.64589411],
       [0.43758721, 0.891773  ]])

In [13]:
np.random.rand(2, 2)

array([[0.96366276, 0.38344152],
       [0.79172504, 0.52889492]])

In [14]:
# Torch seed
torch.manual_seed(0)
torch.rand(2, 2)


 0.4963  0.7682
 0.0885  0.1320
[torch.FloatTensor of size 2x2]

In [15]:
torch.manual_seed(0)
torch.rand(2, 2)


 0.4963  0.7682
 0.0885  0.1320
[torch.FloatTensor of size 2x2]

In [16]:
torch.rand(2, 2)


 0.3074  0.6341
 0.4901  0.8964
[torch.FloatTensor of size 2x2]

### Seed for GPU is set this way

In [17]:
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(0)

## 1.4 Numpy to Torch Bridge

### Numpy to Torch

In [18]:
## Numpy array
np_array = np.ones((2, 2))

In [19]:
np_array

array([[1., 1.],
       [1., 1.]])

In [20]:
## Convert to Torch Tensor
torch_tensor = torch.from_numpy(np_array)

In [21]:
print(torch_tensor)


 1  1
 1  1
[torch.DoubleTensor of size 2x2]



In [22]:
## Datatypes matter
np_array_new = np.ones((2, 2), dtype=np.int8)
torch.from_numpy(np_array_new)

RuntimeError: can't convert a given np.ndarray to a tensor - it has an invalid type. The only supported types are: double, float, int64, int32, and uint8.

In [23]:
## Datatypes matter
np_array_new = np.ones((2, 2), dtype=np.int64)
torch.from_numpy(np_array_new)


 1  1
 1  1
[torch.LongTensor of size 2x2]

In [24]:
## Datatypes matter
np_array_new = np.ones((2, 2), dtype=np.int32)
torch.from_numpy(np_array_new)


 1  1
 1  1
[torch.IntTensor of size 2x2]

### Torch to Numpy

In [25]:
torch_tensor = torch.ones(2, 2)

In [26]:
type(torch_tensor)

torch.FloatTensor

In [27]:
torch_to_numpy = torch_tensor.numpy()

In [28]:
type(torch_to_numpy)

numpy.ndarray

## 1.5 Tensors on CPU vs GPU

In [29]:
# CPU
tensor_cpu = torch.ones(2, 2)

In [30]:
# CPU to GPU
if torch.cuda.is_available():
    tensor_cpu.cuda()

In [31]:
# GPU to CPU
tensor_cpu.cpu()


 1  1
 1  1
[torch.FloatTensor of size 2x2]

## 1.6 Tensor Operations

### Resizing Tensor

In [32]:
a = torch.ones(2, 2)
print(a)


 1  1
 1  1
[torch.FloatTensor of size 2x2]



In [33]:
print(a.size())

torch.Size([2, 2])


In [34]:
a.view(4)  # change to different sizes using view


 1
 1
 1
 1
[torch.FloatTensor of size 4]

In [35]:
a.view(4).size()

torch.Size([4])

### Element Wise Addition

In [36]:
a = torch.ones(2, 2)
print(a)


 1  1
 1  1
[torch.FloatTensor of size 2x2]



In [37]:
b = torch.ones(2, 2)
print(b)


 1  1
 1  1
[torch.FloatTensor of size 2x2]



In [38]:
c = a + b  # Way 1
print(c)


 2  2
 2  2
[torch.FloatTensor of size 2x2]



In [39]:
c = torch.add(a, b) # Way 2
print(c)


 2  2
 2  2
[torch.FloatTensor of size 2x2]



In [40]:
# In Place Addition
print("Old c tensor")
print(c)

c.add_(a)

print("-" * 60)
print("New c tensor")
print(c)

Old c tensor

 2  2
 2  2
[torch.FloatTensor of size 2x2]

------------------------------------------------------------
New c tensor

 3  3
 3  3
[torch.FloatTensor of size 2x2]



### Element Wise Subtraction

In [41]:
print(a)
print(b)


 1  1
 1  1
[torch.FloatTensor of size 2x2]


 1  1
 1  1
[torch.FloatTensor of size 2x2]



In [42]:
a - b


 0  0
 0  0
[torch.FloatTensor of size 2x2]

In [43]:
# not in-place
print(a.sub(b))
print(a)


 0  0
 0  0
[torch.FloatTensor of size 2x2]


 1  1
 1  1
[torch.FloatTensor of size 2x2]



In [44]:
# inplace
print(a.sub_(b))
print(a)


 0  0
 0  0
[torch.FloatTensor of size 2x2]


 0  0
 0  0
[torch.FloatTensor of size 2x2]



### Element Wise Multiplication

In [45]:
a = torch.ones(2, 2)
print(a)


 1  1
 1  1
[torch.FloatTensor of size 2x2]



In [46]:
b = torch.zeros(2, 2)
b


 0  0
 0  0
[torch.FloatTensor of size 2x2]

In [47]:
a * b


 0  0
 0  0
[torch.FloatTensor of size 2x2]

In [48]:
# Not in place
print(torch.mul(a, b))
print(a)


 0  0
 0  0
[torch.FloatTensor of size 2x2]


 1  1
 1  1
[torch.FloatTensor of size 2x2]



In [49]:
# In place
print(a.mul_(b))
print(a)


 0  0
 0  0
[torch.FloatTensor of size 2x2]


 0  0
 0  0
[torch.FloatTensor of size 2x2]



### Element Wise Division

In [50]:
a = torch.ones(2, 2)
b = torch.zeros(2, 2)

In [51]:
b / a


 0  0
 0  0
[torch.FloatTensor of size 2x2]

In [52]:
# Inplace
b.div_(a)


 0  0
 0  0
[torch.FloatTensor of size 2x2]

### Tensor Mean

In [53]:
a = torch.Tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
a.size()

torch.Size([10])

In [54]:
a.mean(dim=0)


 5.5000
[torch.FloatTensor of size 1]

In [55]:
a.mean(dim=1)

RuntimeError: dimension out of range (expected to be in range of [-1, 0], but got 1)

In [56]:
a = torch.Tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 
                  [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]])

In [57]:
a.size()

torch.Size([2, 10])

In [58]:
a.mean(dim=1)


 5.5000
 5.5000
[torch.FloatTensor of size 2]

### Tensor Standard Deviation

In [59]:
a = torch.Tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
a.std(dim=0)


 3.0277
[torch.FloatTensor of size 1]

---